Repository Code-A2Z/jarvis, pull requests merged in 2024-10, with the labels that each got.

#122 Added to-do list
  src/apps/pages/programs/SimplePrograms/toDoList.py
Labels: bug 🐛, Requested Changes ⚙️

#121 feat: music player
  requirements.txt
  src/apps/pages/programs/ApiPrograms/music.py
Labels: Requested Changes ⚙️

#138 Added Minesweeper Game
  src/apps/pages/programs/Games/minesweeper.py
Labels: hacktoberfest-accepted

#146 Integrated Wolfram Alpha API to enable mathematical expression evaluation
  src/apps/pages/programs/ApiPrograms/calculator.py
Labels: Requested Changes ⚙️, hacktoberfest-accepted

#161 Add Cryptocurrency Data API under Programs for API
  src/apps/pages/programs/ApiPrograms/cryptos.py
Labels: Approved ✔️, Code Addition ✒️, gssoc-ext, hacktoberfest-accepted, level3

#136 Fixed Brain tumor code
  src/apps/pages/models/HealthCareModels/BrainTumorModel/brainTumorModel.py
Labels: bug 🐛, Requested Changes ⚙️, hacktoberfest-accepted

#173 Added Text-To-Image Generation Feature
  src/apps/pages/programs/ImageGenerators/textToImageGenerator.py
Labels: Model Addition 🤖, gssoc-ext, hacktoberfest-accepted, level3

#181 Fixes findIP and myLocation to get session user's IP and other geo information
  src/apps/pages/programs/SimplePrograms/findIP.py
  src/apps/pages/programs/SimplePrograms/myLocation.py
Labels: Requested Changes ⚙️, Priority: Medium, gssoc-ext, hacktoberfest-accepted, level3

#183 TextSummarization In continuation to PR #156
  requirements.txt
  src/apps/pages/models/ChatBotModels/TextSummarizationModel/textSummarizationModel.py
Labels: Priority: Medium, Model Addition 🤖, gssoc-ext, hacktoberfest-accepted, level2

#184 Add Contributor Section in Readme.md
  README.md
Labels: enhancement 🧑‍💻, Priority: Medium, gssoc-ext, hacktoberfest-accepted, level1

#165 Added Password Strength Validation (8 Characters, Special Character, and Digit)
  src/auth/signup.py
Labels: enhancement 🧑‍💻, Requested Changes ⚙️, Priority: High, gssoc-ext, hacktoberfest-accepted, level2

#190 add-anime-in-api-programs
  src/apps/pages/programs/ApiPrograms/anime.py
Labels: Approved ✔️, Code Addition ✒️, gssoc-ext, hacktoberfest-accepted, level2

#195 RecipeFinder
  src/apps/pages/programs/ApiPrograms/recipeFinder.py
Labels: Approved ✔️, Code Addition ✒️, gssoc-ext, hacktoberfest-accepted, level2

#197 Fix and enhance mylocation under simple programs
  src/apps/pages/programs/SimplePrograms/myLocation.py
Labels: bug 🐛, Approved ✔️, gssoc-ext, hacktoberfest-accepted, level2

#202 Add url shortener
  src/apps/pages/programs/SimplePrograms/urlShortener.py
Labels: Code Addition ✒️, gssoc-ext, hacktoberfest-accepted, level2

#203 Memory game
  src/apps/pages/programs/Games/memoryGame.py
Labels: Code Addition ✒️, gssoc-ext, hacktoberfest-accepted, level2

#211 Added speech recognition in text-to-image generator program
  requirements.txt
  src/apps/pages/programs/ImageGenerators/speech_textToImageGenerator.py
  src/apps/pages/programs/ImageGenerators/textToImageGenerator.py
Labels: enhancement 🧑‍💻, Approved ✔️, gssoc-ext, hacktoberfest-accepted, level2
