Repository Code-A2Z/jarvis, pull requests merged in 2024-07, with the labels that each got.

#62 Add tic tac toe
  src/apps/pages/programs/Games/tictactoe.py
  src/apps/pages/programs/games.py
  src/utils/functions.py
Labels: bug 🐛, Requested Changes ⚙️

#84 chore: update .gitignore to ignore virtual environment folder
  .gitignore
  README.md
Labels: bug 🐛, Requested Changes ⚙️

#86 Facts API program
  src/apps/pages/programs/ApiPrograms/fact.py
  src/apps/pages/programs/apiProgram.py
Labels: bug 🐛, Requested Changes ⚙️

#90 Added QR Code Generator Program in Jarvis
  requirements.txt
  src/apps/pages/programs/ImageGenerators/qr_code_generator.py
  src/apps/pages/programs/imageProgram.py
Labels: bug 🐛, Requested Changes ⚙️

#91 Calculator Integration
  README.md
  src/apps/pages/programs/SimplePrograms/calculator.py
  src/apps/pages/programs/simpleProgram.py
Labels: Requested Changes ⚙️

#92 World clock
  src/apps/pages/programs/SimplePrograms/worldClock.py
  src/apps/pages/programs/simpleProgram.py
Labels: Requested Changes ⚙️

#94 feat : quotes.py
  src/apps/pages/programs/ApiPrograms/quotes.py
  src/apps/pages/programs/apiProgram.py
Labels: Requested Changes ⚙️

#97 Unit Converter Program
  requirements.txt
  src/apps/pages/programs/ApiPrograms/unit_converter.py
  src/apps/pages/programs/apiProgram.py
Labels: bug 🐛, Requested Changes ⚙️

#103 Added Internet Speed Test program
  .gitignore
  requirements.txt
  src/apps/pages/programs/SimplePrograms/Internet_Speed_Test.py
  src/apps/pages/programs/simpleProgram.py
Labels: bug 🐛, Requested Changes ⚙️

#106 feat : graph plotter
  requirements.txt
  src/apps/pages/programs/SimplePrograms/graph.py
  src/apps/pages/programs/simpleProgram.py
Labels: question❓, Requested Changes ⚙️
