Repository Code-A2Z/jarvis, pull requests merged in 2025-01, with the labels that each got.

#251 Adding Hangman Game
  src/apps/pages/programs/Games/hangman.py
Labels: INTERMEDIATE, SWOC, Status: Review Ongoing

#252 2048 Game
  src/apps/pages/programs/Games/the2048Game.py
Labels: ADVANCE, Status: Requested Changes, SWOC

#254 adding dodge the block game
  src/apps/pages/programs/Games/dodgeGame.py
Labels: INTERMEDIATE, SWOC, Status: Review Ongoing

#258 Update mongodb.py
  database/mongodb.py
Labels: question❓, Status: Review Ongoing

#263 Quiz Generator Game
  src/apps/pages/programs/Games/quizGame.py
Labels: Status: Review Ongoing

#262 Added Support for segment anything model
  .streamlit/secrets.example.toml
  requirements.txt
  src/apps/pages/models/ObjectDetectionModels/segmentAnythingModel.py
Labels: question❓, Status: Review Ongoing

#267 Improved logic of Tic Tac Toe
  src/apps/pages/programs/Games/ticTacToe.py
Labels: Status: Review Ongoing

#259 Add scientific calculator feature
  src/apps/pages/programs/scientificCalculator.py
Labels: ADVANCE, SWOC, Status: Review Ongoing

#276 dog
  .streamlit/secrets.example.toml
  src/apps/pages/models/ObjectDetectionModels/dogBreedClassificationModel.py
Labels: Status: Review Ongoing
